version: 0.0

containers:
  main:
    phases:
      pre_build:
        commands:
          - echo 'Inside Ruby Source Directory'
          - gem install rspec
      during_build:
        commands:
          - echo 'Compiling the Ruby Code'
          - rspec HelloWorld_spec.rb
      post_build:
        commands:
          - echo "Would deploy here"
    artifacts:
      type: zip
      files:
        - 'HelloWorld.rb'